<div class="responsive-menu" data-putinto="responsive-header">
	<span class="close-reposive"><i class="la la-close"></i></span>
	<div class="logo"><a href="/" title=""><img height="52px" src="/images/logo.png" alt="" /></a></div>
	<ul>
		<li class="menu">
			<a href="/" title="">Home</a>
		</li>
		<li class="menu-item-has-children">
			<a href="javascript:void(0)" title="">Apps</a>
			<ul class="appMenuList">

			</ul>
		</li>
		<li><a href="/attributes.html" title="Attributes">Attributes Explained</a></li>
		<li><a href='https://wallets.substack.com'>Newsletter</a></li>
		<li><a href='/dont-track-web3.html'>Don't Track Web3</a></li>
		<li><a href="mailto:contact@bitfalls.com" title="">Contact Us</a></li>
	</ul>
</div>
<ul class="normal-menu" data-putinto="header-menu">
	<li class="menu">
		<a href="/" title="">Home</a>
	</li>
	<li class="menu-item-has-children">
		<a href="/" title="">Apps</a>
		<ul class="appMenuList">

		</ul>
	</li>
	<li><a href="/attributes.html" title="Attributes">Attributes Explained</a></li>
	<li><a href='https://wallets.substack.com'>Newsletter</a></li>
	<li><a href='/dont-track-web3.html'>Don't Track Web3</a></li>
	<li><a href="mailto:contact@bitfalls.com" title="">Contact Us</a></li>
</ul>
<div class="block remove-top no-layer" data-putinto="footer">

				<div class="bottom-line dark">
					<div class="container">
						<span>Copyright Bitfalls.com © 2019. All Rights Reserved | <a
								href="mailto:contact@bitfalls.com">contact@bitfalls.com</a> | Made by <a
								href="https://bruno.id">Bruno</a></span>
						<ul class="social-links">
							<li><a href="https://twitter.com/bitfalls" title="Bitfalls Twitter"><i
										class="la la-twitter"></i></a></li>
						</ul>
					</div>
				</div>
			</div>